env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  mapboxgl: readonly
ignorePatterns:
  - node_modules/
  - web_modules/
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: {}
